taskmanager/account/urls.py
from django.urls import path
from account.views import UserLoginView, UserLogoutView


app_name = 'account'

urlpatterns = [
    path('login', UserLoginView.as_view(), name='login'),
    path('logout', UserLogoutView.as_view(), name='logout')
]

taskmanager/main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.index, name='home'),
    path('about', views.about, name='about'),
    path('create', views.create, name='create'),
    path('delete', views.delete, name='delete')
]

taskmanager/taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('account.urls'))
]

taskmanager/account/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

taskmanager/main/models.py
from django.db import models


class Task(models.Model):
    title = models.CharField('Name', max_length=50)
    task = models.TextField('Description')

    def __str__(self):
        return self.title


    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

taskmanager/account/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class UserLoginForm(AuthenticationForm):
    ...


class UserRegisterForm(UserCreationForm):
    ...

taskmanager/main/forms.py
from .models import Task
from django.forms import ModelForm, TextInput, Textarea


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["title", "task"]
        widgets = {
            "title": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите название'
            }),
            "task": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите описание'
            }),
        }

taskmanager/account/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from account.forms import UserLoginForm, UserRegisterForm


class UserLogoutView(LogoutView):
    next_page = reverse_lazy('main:home')


class UserLoginView(LoginView):
    template_name = 'account/login.html'
    authentication_form = UserLoginForm
    redirect_authenticated_user = True
    next_page = reverse_lazy('main:home')

taskmanager/main/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import Task
from .forms import TaskForm
from django.shortcuts import reverse


def index(request):
    tasks = Task.objects.order_by('-id')
    return render(request, 'main/index.html', {'title': 'Главная страница сайта', 'tasks': tasks})

def about(request):
    return render(request, 'main/about.html')

def create(request):
    error = ''
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:home'))
        else:
            error = 'Форма неверная'

    form = TaskForm()
    context = {
        'form': form,
        'error': error
    }
    return render(request, 'main/create.html', context)


def delete(request):
    Task.objects.all().delete()
    return HttpResponseRedirect(reverse('main:home'))

taskmanager/main/templates/main/about.html
{% extends 'main/base.html' %}

{% block title %}
AMOGUS
{% endblock %}

{% block content %}
    <h1>А че про нас?</h1>
    <p>У нас все норм.</p>
    <p>мем</p>
{% endblock %}

taskmanager/main/templates/main/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor" data-darkreader-inline-fill="" style="--darkreader-inline-fill: currentColor;"></path></svg>
        <span class="fs-4">Aboba</span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          <a class="p-2 text-dark" href="{% url 'home' %}">Домой</a>
          <a class="p-2 text-dark" href="{% url 'about' %}">Про нас</a>
          <a class="p-2 text-dark" href="{% url 'create' %}">Создать таск</a>
      </nav>
      <a class="btn btn-outline-primary" href="#">Sign up</a>
    </div>
    {% block content %}{% endblock %}
</body>
</html>

taskmanager/main/templates/main/create.html
{% extends 'main/base.html' %}

{% block title %}
Создать таск
{% endblock %}

{% block content %}
    <h1>Создать таск</h1>
    <p>У нас все норм.</p>
    <form method="post">
        {% csrf_token %}
        {{ form.title }}<br>
        {{ form.task }}<br>
        <button type="submit" class="btn btn-success">Добавить</button>
        <span>{{ error }}</span>
    </form>
{% endblock %}

taskmanager/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
    <h1>Главная страница</h1>
    {% if tasks %}
        {% for el in tasks %}
            <div class="alert alert-warning mt-2">
                <h3>{{ el.title }}</h3>
                <p>{{ el.task }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p>Задания отсутсвуют :)</p>
    {% endif %}
{% endblock %}

taskmanager/templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor" data-darkreader-inline-fill="" style="--darkreader-inline-fill: currentColor;"></path></svg>
        <span class="fs-4">Aboba</span>
      </a>

      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          <a class="p-2 text-dark" href="{% url 'main:home' %}">Домой</a>
          <a class="p-2 text-dark" href="{% url 'main:about' %}">Про нас</a>
          <a class="p-2 text-dark" href="{% url 'main:create' %}">Создать таск</a>
      </nav>
        {% if user.is_authenticated %}
            <a class="btn btn-outline-primary" href="{% url 'account:logout' %}">Sign out</a>
        {% else %}
            <a class="btn btn-outline-primary" href="{% url 'account:login' %}">Sign in</a>


        {% endif %}
    </div>
    {% block content %}{% endblock %}
</body>
</html>

taskmanager/templates/main/about.html
{% extends 'base.html' %}

{% block title %}
AMOGUS
{% endblock %}

{% block content %}
    <h1>А че про нас?</h1>
    <p>У нас все норм.</p>
    <p>мем</p>
{% endblock %}

taskmanager/templates/main/create.html
{% extends 'base.html' %}

{% block title %}
Создать таск
{% endblock %}

{% block content %}
        <form method="post">

     {% csrf_token %}

      <label for="task">

        {{form.title}}
          {{form.task}}

          <button type="submit">Добавить</button>

      </label>
    </form>

{% endblock %}

taskmanager/templates/main/index.html
{% extends 'base.html' %}

{% block title %}
{{ title }}
{% endblock %}

{% block content %}
    <h1>Главная страница</h1>
    {% if tasks %}
        <a class="p-2 text-dark" href="{% url 'main:delete' %}">
            удалить все таски
        </a>

        {% for el in tasks %}
            <div class="alert alert-warning mt-2">
                <h3>{{ el.title }}</h3>
                <p>{{ el.task }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p>Задания отсутсвуют :)</p>
    {% endif %}



{% endblock %}